In [19]:
import pandas as pd
from pathlib import Path

# Ruta al archivo accidentes.csv
RUTA_ACCIDENTES = Path("../Datos/Staging/accidentes_staging_enriquecido.csv")

# Leer el CSV
accidentes = pd.read_csv(RUTA_ACCIDENTES, parse_dates=["TW"])

# Mostrar primeras 5 filas
accidentes.head()

C:\Users\camil\AppData\Local\Temp\ipykernel_18640\1495999992.py:8: DtypeWarning: Columns (0: RADICADO, 1: CBML) have mixed types. Specify dtype option on import or set low_memory=False.
  accidentes = pd.read_csv(RUTA_ACCIDENTES, parse_dates=["TW"])

,Lon,Lat,OBJECTID,RADICADO,HORA,Dia_sem,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,6.185473,514618,1565408,03:00 AM,DOMINGO,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,6.186579,514675,1565786,04:00 PM,DOMINGO,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,6.287505,514674,1565185,01:30 AM,DOMINGO,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,6.284049,507561,20,08:30 AM,DOMINGO,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,6.214653,515610,1565438,07:00 PM,DOMINGO,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

In [20]:
print(accidentes.columns)

Index(['Lon', 'Lat', 'OBJECTID', 'RADICADO', 'HORA', 'Dia_sem', 'PERIODO',
       'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'CBML', 'TIPO_GEOCOD',
       'GRAVEDAD', 'BARRIO', 'COMUNA', 'DISENO', 'Mes', 'Dia', 'FECHA',
       'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num',
       'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin',
       'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext',
       'prom_accidentes_historico_barrio'],
      dtype='str')

## Tabla `features_accidentes`

Copia del dataset con One-Hot de `CLASE`, sin `HORA` ni `Dia_sem` (ya representadas con `hora_sin`/`hora_cos` y `dia_semana_sin`/`dia_semana_cos`).

In [ ]:
COLUMNAS_ELIMINAR = ["HORA", "Dia_sem"]

faltantes = [c for c in COLUMNAS_ELIMINAR if c not in accidentes.columns]
if faltantes:
    print(f"Advertencia: no se encontraron columnas {faltantes}")

features_accidentes = accidentes.drop(columns=COLUMNAS_ELIMINAR, errors="ignore").copy()

print("Columnas eliminadas (información duplicada):")
for col in COLUMNAS_ELIMINAR:
    if col in accidentes.columns:
        print(f"  - {col}")

print(f"\naccidentes:          {accidentes.shape[0]:,} filas × {accidentes.shape[1]} columnas")
print(f"features_accidentes: {features_accidentes.shape[0]:,} filas × {features_accidentes.shape[1]} columnas")
print(f"\nColumnas de features_accidentes ({len(features_accidentes.columns)}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

Columnas eliminadas (información duplicada):
  - HORA
  - Dia_sem

accidentes:          125,122 filas × 35 columnas
features_accidentes: 125,122 filas × 33 columnas

Columnas de features_accidentes (33):
['Lon', 'Lat', 'OBJECTID', 'RADICADO', 'PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'CBML', 'TIPO_GEOCOD', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'DISENO', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,Lon,Lat,OBJECTID,RADICADO,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,CBML,TIPO_GEOCOD,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,6.185473,514618,1565408,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,8000,Malla vial,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,6.186579,514675,1565786,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,8000,Malla vial,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,6.287505,514674,1565185,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,0607,Malla vial,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,6.284049,507561,20,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,60980380285,Nomenclatura con Interior,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,6.214653,515610,1565438,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,0916,Malla vial cruce invertido,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar `TIPO_GEOCOD`

Tiene miles de categorías casi únicas (geocodificación muy específica); no conviene para el modelo. Se quita de `features_accidentes`.

In [22]:
COL_ELIMINAR = "TIPO_GEOCOD"

cols_antes = len(features_accidentes.columns)
filas = len(features_accidentes)

print("ANTES:")
print(f"  Columnas: {cols_antes}")
print(f"  ¿Existe {COL_ELIMINAR}? {COL_ELIMINAR in features_accidentes.columns}")

features_accidentes = features_accidentes.drop(columns=[COL_ELIMINAR], errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {filas:,} (sin cambio)")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 33
  ¿Existe TIPO_GEOCOD? True

DESPUÉS:
  Columnas: 32  (cambio: -1)
  Filas: 125,122 (sin cambio)

Columnas actuales (32):
['Lon', 'Lat', 'OBJECTID', 'RADICADO', 'PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'CBML', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'DISENO', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,Lon,Lat,OBJECTID,RADICADO,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,CBML,GRAVEDAD,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,6.185473,514618,1565408,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,8000,SOLO DAÑOS,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,6.186579,514675,1565786,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,8000,HERIDO,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,6.287505,514674,1565185,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,0607,HERIDO,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,6.284049,507561,20,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,60980380285,MUERTO,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,6.214653,515610,1565438,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,0916,HERIDO,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar `OBJECTID`

Identificador interno del GIS (ArcGIS); no aporta al modelo y no debe usarse como variable predictora.

In [23]:
COL_ELIMINAR = "OBJECTID"

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")

features_accidentes = features_accidentes.drop(columns=[COL_ELIMINAR], errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 32

DESPUÉS:
  Columnas: 31  (cambio: -1)
  Filas: 125,122

Columnas actuales (31):
['Lon', 'Lat', 'RADICADO', 'PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'CBML', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'DISENO', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,Lon,Lat,RADICADO,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,CBML,GRAVEDAD,BARRIO,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,6.185473,1565408,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,8000,SOLO DAÑOS,cabecerasanantoniodeprado,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,6.186579,1565786,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,8000,HERIDO,cabecerasanantoniodeprado,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,6.287505,1565185,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,0607,HERIDO,kennedy,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,6.284049,20,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,60980380285,MUERTO,areadeexpansionpajarito,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,6.214653,1565438,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,0916,HERIDO,asomaderano3,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar `RADICADO`

Número de radicado del caso en el sistema oficial; es un identificador administrativo, no una variable predictiva.

In [24]:
COL_ELIMINAR = "RADICADO"

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")

features_accidentes = features_accidentes.drop(columns=[COL_ELIMINAR], errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 31

DESPUÉS:
  Columnas: 30  (cambio: -1)
  Filas: 125,122

Columnas actuales (30):
['Lon', 'Lat', 'PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'CBML', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'DISENO', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,Lon,Lat,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,CBML,GRAVEDAD,BARRIO,COMUNA,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,6.185473,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,8000,SOLO DAÑOS,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,6.186579,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,8000,HERIDO,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,6.287505,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,0607,HERIDO,kennedy,Doce de Octubre,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,6.284049,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,60980380285,MUERTO,areadeexpansionpajarito,Corregimiento de San Cristóbal,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,6.214653,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,0916,HERIDO,asomaderano3,Buenos Aires,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar `CBML`

Código de geocodificación/catastro de la dirección; es muy específico y redundante con `DIRECCION`, `BARRIO` y coordenadas.

In [25]:
COL_ELIMINAR = "CBML"

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")

features_accidentes = features_accidentes.drop(columns=[COL_ELIMINAR], errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 30

DESPUÉS:
  Columnas: 29  (cambio: -1)
  Filas: 125,122

Columnas actuales (29):
['Lon', 'Lat', 'PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'DISENO', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,Lon,Lat,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,GRAVEDAD,BARRIO,COMUNA,DISENO,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,6.185473,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,SOLO DAÑOS,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,Tramo de via,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,6.186579,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,HERIDO,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,Tramo de via,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,6.287505,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,HERIDO,kennedy,Doce de Octubre,Tramo de via,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,6.284049,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,MUERTO,areadeexpansionpajarito,Corregimiento de San Cristóbal,NaN,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,6.214653,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,HERIDO,asomaderano3,Buenos Aires,Tramo de via,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar `DISENO`

Columna del dataset original de accidentes; se quita de `features_accidentes` para el modelado.

In [ ]:
COL_ELIMINAR = "DISENO"

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")

features_accidentes = features_accidentes.drop(columns=[COL_ELIMINAR], errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 29

DESPUÉS:
  Columnas: 28  (cambio: -1)
  Filas: 125,122

Columnas actuales (28):
['Lon', 'Lat', 'PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,Lon,Lat,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,GRAVEDAD,BARRIO,COMUNA,Mes,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,6.185473,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,SOLO DAÑOS,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,6.186579,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,HERIDO,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,6.287505,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,HERIDO,kennedy,Doce de Octubre,1,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,6.284049,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,MUERTO,areadeexpansionpajarito,Corregimiento de San Cristóbal,1,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,6.214653,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,HERIDO,asomaderano3,Buenos Aires,1,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar latitud (`Lat`)

Se quita la columna de latitud; se mantiene `Lon` si aún la necesitas para ubicación o join.

In [27]:
# En el dataset la latitud está como "Lat"
COL_ELIMINAR = "Lat"

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")
print(f"  ¿Existe {COL_ELIMINAR}? {COL_ELIMINAR in features_accidentes.columns}")

features_accidentes = features_accidentes.drop(columns=[COL_ELIMINAR], errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 28
  ¿Existe Lat? True

DESPUÉS:
  Columnas: 27  (cambio: -1)
  Filas: 125,122

Columnas actuales (27):
['Lon', 'PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,Lon,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,GRAVEDAD,BARRIO,COMUNA,Mes,Dia,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,-75.648182,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,SOLO DAÑOS,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,-75.648998,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,HERIDO,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,-75.581983,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,HERIDO,kennedy,Doce de Octubre,1,1,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,-75.613491,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,MUERTO,areadeexpansionpajarito,Corregimiento de San Cristóbal,1,1,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,-75.557658,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,HERIDO,asomaderano3,Buenos Aires,1,1,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar longitud (`Lon`)

Se quita la columna de longitud de `features_accidentes`.

In [28]:
COL_ELIMINAR = "Lon"

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")
print(f"  ¿Existe {COL_ELIMINAR}? {COL_ELIMINAR in features_accidentes.columns}")

features_accidentes = features_accidentes.drop(columns=[COL_ELIMINAR], errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 27
  ¿Existe Lon? True

DESPUÉS:
  Columnas: 26  (cambio: -1)
  Filas: 125,122

Columnas actuales (26):
['PERIODO', 'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,GRAVEDAD,BARRIO,COMUNA,Mes,Dia,FECHA,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,2017,CHOQUE,CL 39 D sur CR 66 A,CL S 039 D 066 A 000 00000,SOLO DAÑOS,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,2017-01-01,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,2017,ATROPELLO,CL 38 B sur CR 69,CL S 038 B 069 000 00000,HERIDO,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,2017-01-01,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,2017,CHOQUE,CR 76 CL 91,CR 076 091 000 00000,HERIDO,kennedy,Doce de Octubre,1,1,2017-01-01,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,2017,CHOQUE,CL 66 CR 103 B - 15,CL 066 103 B 015 00000,MUERTO,areadeexpansionpajarito,Corregimiento de San Cristóbal,1,1,2017-01-01,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,2017,CAIDA OCUPANTE,CL 16 CR 28,CL 016 028 000 00000,HERIDO,asomaderano3,Buenos Aires,1,1,2017-01-01,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar `DIRECCION` y `DIRECCION_ENC`

Texto de dirección (original y codificada); redundante con `BARRIO`, `COMUNA` y variables temporales.

In [29]:
COLUMNAS_ELIMINAR = ["DIRECCION", "DIRECCION_ENC"]

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")

features_accidentes = features_accidentes.drop(columns=COLUMNAS_ELIMINAR, errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Eliminadas: {COLUMNAS_ELIMINAR}")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 26

DESPUÉS:
  Columnas: 24  (cambio: -2)
  Eliminadas: ['DIRECCION', 'DIRECCION_ENC']
  Filas: 125,122

Columnas actuales (24):
['PERIODO', 'CLASE', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,PERIODO,CLASE,GRAVEDAD,BARRIO,COMUNA,Mes,Dia,FECHA,Hora_num,TW,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,2017,CHOQUE,SOLO DAÑOS,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,2017-01-01,3,2017-01-01 03:00:00,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,2017,ATROPELLO,HERIDO,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,2017-01-01,16,2017-01-01 16:00:00,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,2017,CHOQUE,HERIDO,kennedy,Doce de Octubre,1,1,2017-01-01,1,2017-01-01 01:00:00,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,2017,CHOQUE,MUERTO,areadeexpansionpajarito,Corregimiento de San Cristóbal,1,1,2017-01-01,8,2017-01-01 08:00:00,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,2017,CAIDA OCUPANTE,HERIDO,asomaderano3,Buenos Aires,1,1,2017-01-01,19,2017-01-01 19:00:00,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar `CLASE` y `GRAVEDAD`

Quitamos la columna original y, si existen, las dummies `clase_*` y `gravedad_*` (no se usan como predictores en el join con clima).

In [30]:
cols_antes = len(features_accidentes.columns)

# Texto original + posibles columnas One-Hot
cols_clase_gravedad = [
    c for c in features_accidentes.columns
    if c in ("CLASE", "GRAVEDAD")
    or c.startswith("clase_")
    or c.startswith("gravedad_")
]

print("ANTES:")
print(f"  Columnas: {cols_antes}")
print(f"  A eliminar ({len(cols_clase_gravedad)}):")
for c in cols_clase_gravedad:
    print(f"    - {c}")

features_accidentes = features_accidentes.drop(columns=cols_clase_gravedad, errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 24
  A eliminar (2):
    - CLASE
    - GRAVEDAD

DESPUÉS:
  Columnas: 22  (cambio: -2)
  Filas: 125,122

Columnas actuales (22):
['PERIODO', 'BARRIO', 'COMUNA', 'Mes', 'Dia', 'FECHA', 'Hora_num', 'TW', 'Dia_Sem_REAL', 'hora_dia', 'dia_semana', 'mes_num', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,PERIODO,BARRIO,COMUNA,Mes,Dia,FECHA,Hora_num,TW,Dia_Sem_REAL,hora_dia,...,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,2017,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,2017-01-01,3,2017-01-01 03:00:00,DOMINGO,3,...,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,2017,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,1,1,2017-01-01,16,2017-01-01 16:00:00,DOMINGO,16,...,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,2017,kennedy,Doce de Octubre,1,1,2017-01-01,1,2017-01-01 01:00:00,DOMINGO,1,...,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,2017,areadeexpansionpajarito,Corregimiento de San Cristóbal,1,1,2017-01-01,8,2017-01-01 08:00:00,DOMINGO,8,...,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,2017,asomaderano3,Buenos Aires,1,1,2017-01-01,19,2017-01-01 19:00:00,DOMINGO,19,...,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Eliminar columnas de fecha/hora redundantes

Quitamos `FECHA`, `Mes`, `Dia_Sem_REAL` y `hora_dia` porque ya están representadas en `TW`, `mes_num`, `dia_semana` y las variables `hora_sin` / `hora_cos`.

In [ ]:
COLUMNAS_ELIMINAR = ["FECHA", "Mes", "Dia_Sem_REAL", "hora_dia", "PERIODO","comuna","Dia","Hora_num","mes_num","dia_semana"]

cols_antes = len(features_accidentes.columns)

print("ANTES:")
print(f"  Columnas: {cols_antes}")

features_accidentes = features_accidentes.drop(columns=COLUMNAS_ELIMINAR, errors="ignore")

cols_despues = len(features_accidentes.columns)

print("\nDESPUÉS:")
print(f"  Columnas: {cols_despues}  (cambio: {cols_despues - cols_antes})")
print(f"  Eliminadas: {COLUMNAS_ELIMINAR}")
print(f"  Filas: {len(features_accidentes):,}")
print(f"\nColumnas actuales ({cols_despues}):")
print(features_accidentes.columns.tolist())

display(features_accidentes.head())

ANTES:
  Columnas: 14

DESPUÉS:
  Columnas: 13  (cambio: -1)
  Eliminadas: ['FECHA', 'Mes', 'Dia_Sem_REAL', 'hora_dia', 'PERIODO', 'comuna', 'Dia', 'Hora_num', 'mes_num', 'dia_semana']
  Filas: 125,122

Columnas actuales (13):
['BARRIO', 'COMUNA', 'TW', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']

,BARRIO,COMUNA,TW,es_fin_semana,es_festivo,hora_sin,hora_cos,dia_semana_sin,dia_semana_cos,dia_ano_sin,dia_ano_cos,comuna_ext,prom_accidentes_historico_barrio
0,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,2017-01-01 03:00:00,1,1,0.707107,0.707107,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
1,cabecerasanantoniodeprado,Corregimiento de San Antonio de Prado,2017-01-01 16:00:00,1,1,-0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,80.0,0.0
2,kennedy,Doce de Octubre,2017-01-01 01:00:00,1,1,0.258819,0.965926,-0.781831,0.62349,0.017213,0.999852,6.0,0.0
3,areadeexpansionpajarito,Corregimiento de San Cristóbal,2017-01-01 08:00:00,1,1,0.866025,-0.500000,-0.781831,0.62349,0.017213,0.999852,60.0,0.0
4,asomaderano3,Buenos Aires,2017-01-01 19:00:00,1,1,-0.965926,0.258819,-0.781831,0.62349,0.017213,0.999852,9.0,0.0

## Exportar `features_accidentes` a CSV

Guardamos la tabla final en la capa **Trusted** para usarla en el join con clima.

In [37]:
from pathlib import Path

RUTA_SALIDA = Path("../Datos/Trusted/features_accidentes.csv")
RUTA_SALIDA.parent.mkdir(parents=True, exist_ok=True)

features_accidentes.to_csv(RUTA_SALIDA, index=False)

print(f"Archivo guardado: {RUTA_SALIDA.resolve()}")
print(f"Filas: {len(features_accidentes):,} | Columnas: {len(features_accidentes.columns)}")
print(f"Columnas: {features_accidentes.columns.tolist()}")

Archivo guardado: C:\Users\camil\OneDrive\Documentos\Aprendizaje de Maquina\Taller\Datos\Trusted\features_accidentes.csv
Filas: 125,122 | Columnas: 13
Columnas: ['BARRIO', 'COMUNA', 'TW', 'es_fin_semana', 'es_festivo', 'hora_sin', 'hora_cos', 'dia_semana_sin', 'dia_semana_cos', 'dia_ano_sin', 'dia_ano_cos', 'comuna_ext', 'prom_accidentes_historico_barrio']